Repository acm-ucr/csa-website, pull requests merged in 2025-01, with the labels that each got.

#15 add about route in app folder
  src/app/about/page.tsx
  src/components/about/About.tsx
Labels: ready for review

#16 Stanleylew5/example
  src/app/events/page.tsx
Labels: ready for review

#19 Add heading component for four pillars title
  src/app/about/page.tsx
  src/components/about/FourPillTitle.tsx
Labels: ready for review

#18 Added Theme Description Component.
  src/app/page.tsx
  src/components/home/XinDescription.tsx
  tailwind.config.ts
Labels: ready for review

#20 Add WhoAreWe component
  src/app/about/page.tsx
  src/components/about/About.tsx
  src/components/about/WhoWeAre.tsx
Labels: ready for review

#22 Add Event Highlights Title Component
  src/app/page.tsx
  src/components/events/EventHighlightsTitle.tsx
Labels: ready for review

#26 ALE00111/nav bar
  package.json
  public/home/csalogo.svg
  public/home/webpageMarker.svg
  src/app/layout.tsx
  src/components/NavBar.tsx
  src/data/navBarData.ts
Labels: ready for review, changes requested

#21 Add Quote Box Component
  public/about/lantern.svg
  src/app/page.tsx
  src/components/home/QuoteBox.tsx
  src/data/quote-data.ts
Labels: ready for review

#28 completed mission statement issue
  package-lock.json
  src/app/page.tsx
  src/components/home/MissionStatement.tsx
Labels: ready for review, changes requested

#50 Add latern on right
  src/app/about/page.tsx
  src/components/about/RightLantern.tsx
Labels: ready for review

#49 Culture Component
  public/about/envelope.webp
  src/app/about/page.tsx
  src/components/about/Culture.tsx
Labels: ready for review, changes requested

#45 Add social component for about page
  public/about/pendant.webp
  src/app/about/page.tsx
  src/components/about/Social.tsx
Labels: ready for review

#48 Add grid for xin description
  public/home/xinimage.svg
  src/components/home/XinDescription.tsx
Labels: ready for review

#53 dragon on left
  package-lock.json
  public/home/Dragon.png
  src/app/page.tsx
Labels: ready for review, changes requested

#66 add pink flower with butterflies to gallery page
  public/gallery/pinkFlower.webp
  src/app/gallery/page.tsx
  src/components/gallery/Gallery.tsx
Labels: ready for review

#73 Add 404 page text
  src/app/not-found.tsx
  src/components/NotFound.tsx
Labels: changes requested

#71 Add funny images on Error Page
  public/not-found/cryingPanda.webp
  public/not-found/pandaWithFlower.webp
  public/not-found/pandaWithWok.webp
  public/not-found/teletubby_po.webp
  src/components/NotFound.tsx
Labels: ready for review

#75 Add board datafile
  public/board/Aidan_Lam.webp
  public/board/Alex_Sin.webp
  public/board/Andrew_Zhang.webp
  public/board/Andy_Banh.webp
  public/board/Anson_Gao.webp
  public/board/Board_group.webp
  public/board/Briana_Lam.webp
  public/board/Caitlyn_Hang.webp
  public/board/Connor_Lau.webp
  public/board/Dominic_Rivera.webp
  public/board/Ingrid_Yee.webp
  public/board/Irene_Li.webp
  public/board/Isabelle_Huang.webp
  public/board/Joshua_Yu.webp
  public/board/Kaelyn_Lam.webp
  public/board/Kathy_Liu.webp
  public/board/Kyle_Chan.webp
  public/board/Marcus_Lee.webp
  public/board/Megan_Ho.webp
  public/board/Mia_Chiang.webp
  public/board/Nathan_Cheung.webp
  public/board/Peter_Hsia.webp
  public/board/Renne_Sanchez.webp
  public/board/Ryan_Hoang.webp
  public/board/Ryan_Lew.webp
  public/board/Ryan_Nguyen.webp
  public/board/Samantha_Lee.webp
  public/board/Yoonah_Choi.webp
  public/board/Yuhan_Shi.webp
  src/data/boardInfo.js
Labels: ready for review

#70 background lanterns 404
  public/not-found/lantern404.webp
  src/app/about/page.tsx
  src/app/board/page.tsx
  src/app/events/page.tsx
  src/app/gallery/page.tsx
  src/components/NotFound.tsx
  src/components/about/AcademicComponent.tsx
  src/components/about/Philanthropy.tsx
  src/components/about/Social.tsx
  src/components/board/Board.tsx
  src/components/events/Calendar.tsx
  src/components/events/EventHighlightsTitle.tsx
  src/components/events/FruitBranch.tsx
  src/components/gallery/Gallery.tsx
  src/components/home/Home.tsx
  src/components/home/QuoteBox.tsx
  src/data/boardInfo.ts
Labels: ready for review, changes requested

#29 Nidu Rahubedde/csa description#2
  src/app/page.tsx
  src/components/home/Header.tsx
  tailwind.config.ts
Labels: changes requested

#85 Add Cherry Tree image on About page
  package-lock.json
  public/about/cherryTree.webp
  src/app/about/page.tsx
  src/components/about/CherryTree.tsx
Labels: ready for review
