Repository acm-ucr/csa-website, pull requests merged in 2025-02, with the labels that each got.

#109 Add BoardCard & Board Component
  public/board/beigeDiamond.webp
  public/board/brownDiamond.webp
  public/board/greyDiamond.webp
  public/board/redDiamond.webp
  src/app/about/page.tsx
  src/app/board/page.tsx
  src/app/globals.css
  src/components/about/Academic.tsx
  src/components/board/Board.tsx
  src/components/board/BoardCard.tsx
  src/data/boardInfo.ts
Labels: ready for review

#110 Mobile Responsiveness
  public/not-found/lantern404.svg
  public/not-found/lantern404.webp
  src/components/NotFound.tsx
Labels: ready for review, changes requested

#113 Add blue flower
  public/gallery/blueFlower.webp
  src/components/gallery/Gallery.tsx
Labels: ready for review

#111 Add Member Experiences component
  public/home/ram.webp
  src/app/page.tsx
  src/components/home/MemberExperienceTitle.tsx
Labels: ready for review

#117 Combine components for Landing page
  src/app/page.tsx
  src/components/home/Header.tsx
  src/components/home/Landing.tsx
  src/components/home/MissionStatement.tsx
Labels: ready for review

#118 add board title
  src/app/board/page.tsx
Labels: ready for review

#114 Add mobile responsiveness of Xin description
  src/components/home/XinDescription.tsx
Labels: ready for review

#115 Add footer mobile responsiveness
  src/components/Footer.tsx
Labels: ready for review

#137 Add nav hover animations
  package-lock.json
  src/components/NavBar.tsx
Labels: ready for review

#136 add path name for nav bar
  src/components/NavBar.tsx
Labels: changes requested

#138 Call title component for calendar
  src/app/events/page.tsx
Labels: ready for review

#140 Fixing quote file format
  src/app/page.tsx
  src/components/home/Quote.tsx
Labels: ready for review

#139 Hide title banner on mobile
  src/components/Title.tsx
Labels: ready for review

#120 Increasing width of quotebox for mobile devices
  src/components/home/QuoteBox.tsx
Labels: ready for review, changes requested

#142 puttting branches in the right place
  src/app/events/page.tsx
  src/components/events/FruitBranch.tsx
Labels: ready for review

#151 restored hover animations in NavBar
  src/components/NavBar.tsx
Labels: ready for review

#155 update favicon
  src/app/favicon.ico
Labels: ready for review

#153 Title Animation
  package-lock.json
  package.json
  public/banner.webp
  public/home/banner.svg
  src/app/page.tsx
  src/components/Title.tsx
  src/components/home/Home.tsx
  src/components/home/MemberExperienceTitle.tsx
Labels: help wanted

#165 Adding animation to board member cards
  package-lock.json
  package.json
  src/components/board/Board.tsx
Labels: ready for review

#122 Inegishi/fourpillar
  src/app/about/page.tsx
  src/components/about/Culture.tsx
  src/components/about/FourPillTitle.tsx
  src/components/about/FourPillars.tsx
Labels: changes requested

#143 fix landing responsiveness
  public/home/RightCloud.svg
  src/components/home/Landing.tsx
Labels: ready for review, changes requested

#163 Add Chinese Association animation
  src/components/home/Landing.tsx
Labels: ready for review

#168 Add absolute positioning to NavBar
  src/components/NavBar.tsx
Labels: ready for review

#187 Remove div
  src/components/board/GroupPhoto.tsx
  src/components/gallery/Event.tsx
Labels: ready for review

#186 remove comment
  src/components/board/GroupPhoto.tsx
Labels: ready for review

#190 Remove flex and flex-col in BoardCard
  src/components/board/BoardCard.tsx
Labels: ready for review

#189 Change csa logo to webp
  public/home/csalogo.svg
  public/home/csalogo.webp
  src/components/Footer.tsx
  src/components/NavBar.tsx
Labels: ready for review

#193 update lantern404 to webp
  public/not-found/lantern404.svg
  public/not-found/lantern404.webp
  src/components/NotFound.tsx
Labels: ready for review

#192 change div to fragment
  src/components/about/WhoWeAre.tsx
Labels: ready for review

#191 destructure NavBar mapping
  src/components/NavBar.tsx
Labels: ready for review

#194 Destructure footer icons
  src/components/Footer.tsx
Labels: ready for review

#188 Updating title prop
  src/app/about/page.tsx
  src/app/board/page.tsx
  src/app/events/page.tsx
  src/app/gallery/page.tsx
  src/components/Title.tsx
Labels: ready for review

#185 Combined NotFound Component to NotFoundPage
  src/app/not-found.tsx
  src/app/page.tsx
  src/components/NotFound.tsx
Labels: ready for review
